version: '3.8'

services:
  auth-service:
    build: ./backend-microservices/auth-service
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    depends_on:
      - postgres

  product-service:
    build: ./backend-microservices/product-service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    depends_on:
      - postgres

  product-catlog:
    build: ./product-catlog  # Path to your frontend directory
    ports:
      - "3000:3000"  # Frontend port (adjust based on your app's port)
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - auth-service  # Ensure auth-service is up before frontend starts
      - product-service  # Ensure product-service is up before frontend starts

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres  # Shared DB for all tenants
    ports:
      - "5432:5432"